id: eeb889ce85b544eea6a8b7ec5e9181b6
title: Toh_152-The_Questions_of_Sagaramati-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-058-001
  eft-text-version: 1.2.1 2020
